### ISSUE TITLE
[Bug] Parsing error loading recipe and Loot table

### ISSUE THREAD

**Issue by R3tr0PAG** [Enchanted-Games/vertical-slabs#4]
Everytime i start my server i get these 2 Errors, idk if this has/or will be fixed.

Minecraft Version: 1.18.1
Fabric Version: 0.13.3
Mod Version: 1.3

[Worker-Main-5/ERROR]: Parsing error loading recipe enchanted-vertical-slabs:vertical_umbralith_tree_slab
com.google.gson.JsonSyntaxException: Unknown item 'enchanted-vertical-slabs:vertical_umbralith_tree_slab'
at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[server-intermediary.jar:?]
at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[server-intermediary.jar:?]
at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[server-intermediary.jar:?]
at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:273) ~[server-intermediary.jar:?]
at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:260) ~[server-intermediary.jar:?]
at net.minecraft.class_1863.method_17720(class_1863.java:126) ~[server-intermediary.jar:?]
at net.minecraft.class_1863.method_20705(class_1863.java:55) ~[server-intermediary.jar:?]
at net.minecraft.class_1863.method_18788(class_1863.java:34) ~[server-intermediary.jar:?]
at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at net.minecraft.class_4014$1.method_18374(class_4014.java:53) ~[server-intermediary.jar:?]
at net.minecraft.class_4014$1.method_18352(class_4014.java:50) ~[server-intermediary.jar:?]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) [?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

Also this one

[Worker-Main-5/ERROR]: Couldn't parse loot table enchanted-vertical-slabs:blocks/vertical_umbralith_tree_slab
java.lang.IllegalArgumentException: Can't find block enchanted-vertical-slabs:vertical_umbralith_tree_slab
at net.minecraft.class_212$class_214.method_17937(class_212.java:79) ~[server-intermediary.jar:?]
at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
at net.minecraft.class_212$class_214.method_910(class_212.java:79) ~[server-intermediary.jar:?]
at net.minecraft.class_212$class_214.method_517(class_212.java:68) ~[server-intermediary.jar:?]
at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[server-intermediary.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar:?]
at net.minecraft.class_3518.method_15291(class_3518.java:448) ~[server-intermediary.jar:?]
at net.minecraft.class_3518.method_15283(class_3518.java:466) ~[server-intermediary.jar:?]
at net.minecraft.class_120$class_123.method_528(class_120.java:98) ~[server-intermediary.jar:?]
at net.minecraft.class_120$class_123.method_517(class_120.java:88) ~[server-intermediary.jar:?]
at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[server-intermediary.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar:?]
at net.minecraft.class_3518.method_15291(class_3518.java:448) ~[server-intermediary.jar:?]
at net.minecraft.class_3518.method_15283(class_3518.java:466) ~[server-intermediary.jar:?]
at net.minecraft.class_85$class_90.method_441(class_85.java:149) ~[server-intermediary.jar:?]
at net.minecraft.class_85$class_90.method_424(class_85.java:129) ~[server-intermediary.jar:?]
at net.minecraft.class_79$class_5337.method_29319(class_79.java:86) ~[server-intermediary.jar:?]
at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[server-intermediary.jar:?]
at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[server-intermediary.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar:?]
at net.minecraft.class_3518.method_15291(class_3518.java:448) ~[server-intermediary.jar:?]
at net.minecraft.class_3518.method_15272(class_3518.java:456) ~[server-intermediary.jar:?]
at net.minecraft.class_55$class_57.method_358(class_55.java:173) ~[server-intermediary.jar:?]
at net.minecraft.class_55$class_57.deserialize(class_55.java:169) ~[server-intermediary.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar:?]
at net.minecraft.class_3518.method_15291(class_3518.java:448) ~[server-intermediary.jar:?]
at net.minecraft.class_3518.method_15283(class_3518.java:466) ~[server-intermediary.jar:?]
at net.minecraft.class_52$class_54.method_340(class_52.java:213) ~[server-intermediary.jar:?]
at net.minecraft.class_52$class_54.deserialize(class_52.java:209) ~[server-intermediary.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.8.jar:?]
at net.minecraft.class_60.method_20711(class_60.java:44) ~[server-intermediary.jar:?]
at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
at net.minecraft.class_60.method_20712(class_60.java:42) ~[server-intermediary.jar:?]
at net.minecraft.class_60.method_18788(class_60.java:17) ~[server-intermediary.jar:?]
at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at net.minecraft.class_4014$1.method_18374(class_4014.java:53) ~[server-intermediary.jar:?]
at net.minecraft.class_4014$1.method_18352(class_4014.java:50) ~[server-intermediary.jar:?]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) [?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**Comment by Enchanted-Games** [comment]
I believe this is caused by the recipes for the better end vertical slabs always being loaded, even if better end is not installed. I will see if there is a way to prevent the errors but i'm not sure yet

**Comment by R3tr0PAG** [comment]
Well, i do have BetterEnd installed so i'm guessing this shouldn't appear.

**Comment by Enchanted-Games** [comment]
The issue is that the block loot table "enchanted-vertical-slabs:vertical_umbralith_tree_slab" should be called "enchanted-vertical-slabs:vertical_umbrella_tree_slab" . It also calls for an item that doesn't exist.
The issue will remain open either until I release a fix or I find out how to stop errors showing if better end isn't installed

**Comment by SplendidAlakey** [comment]
> find out how to stop errors showing if better end isn't installed

That would be amazing. My server log files are over 11k lines simply because I don't use any of the supported mods.

**Comment by Enchanted-Games** [comment]
Fixed in v1.4 
Seperated the BetterEnd slabs into their own mod

**Comment by SplendidAlakey** [comment]
I'm still getting error spam with 1.4.0: https://gist.github.com/Footage2-Amply-Pounce/9a508ab7dfcb0a129f69b14cb43fb4f9

**Comment by Enchanted-Games** [comment]
Those error logs don't seem to be realted to any of my mods, try disabling some other mods to see if any are causing the error spam

**Comment by R3tr0PAG** [comment]
Well, idk about that.
He does have the newest version of Enchanted-Vertical-Slabs = 1.4.0
and he does not have BetterEnd installed, yet he still get's the error's "[22:27:54] [Render thread/ERROR]: Parsing error loading recipe enchanted-vertical-slabs:vertical_tenanea_slab
com.google.gson.JsonSyntaxException: Unknown item 'betterend:tenanea_planks' "

I think it could be that he had BetterEnd installed and removed it (which could cause some issues) but i don't think that's the case here.

**Comment by Enchanted-Games** [comment]
Didn't see that, I must have left a better end recipe in by accident

**Comment by R3tr0PAG** [comment]
there are actually a lot of these after the 22:27:54 time

**Comment by SplendidAlakey** [comment]
Loaded with just Fabric API + Enchanted Vertical Slabs 1.4.0, still getting the log spam: https://gist.github.com/Footage2-Amply-Pounce/8d3d4878a93d7826b96108b1ff99ef11

This time I also tested it in a new world so no past recipes could've existed.

**Comment by Enchanted-Games** [comment]
The better end recipes were left in v1.4 meaning they call for items that don’t exist. I’ll try to get a fix out soon

**Comment by Enchanted-Games** [comment]
Fixed in v1.4.1
